### PR TITLE
Remove logs

### PR DESCRIPTION
**Pull request by bahlo**
- Export OTEL methods for advanced configurations
- Make script example complete

### CODE REVIEW

**Comment by schehata** [comment]
All looks legit, maybe there is one thing we can change,
to remove those from resources:

```js
[SemanticResourceAttributes.TELEMETRY_SDK_NAME]: 'prisma-axiom',
[SemanticResourceAttributes.TELEMETRY_SDK_VERSION]: Version,
```

We can maybe add `[SemanticResourceAttributes.SERVICE_VERSION]`, I guess the value could be `process.env.npm_package_version`, but I haven't tried that variable myself.

**Review by schehata — APPROVED** [review]

**Comment by schehata** [comment]
@bahlo I faced some typescript errors for a while, and saw the warnings for prisma 4.3.1 not compatible with 4.2.1. But after deleting my node modules and installing again, the errors disappeared. But I don't see that traces are sent. still debugging the problem.

**Comment by schehata** [comment]
> @bahlo I faced some typescript errors for a while, and saw the warnings for prisma 4.3.1 not compatible with 4.2.1. But after deleting my node modules and installing again, the errors disappeared. But I don't see that traces are sent. still debugging the problem.

I am not sure whats changed than before, but I read somewhere that registering the provider should happen before importing PrismaClient

**Comment by schehata** [comment]
ok, examples are working. I just needed to convert my .env file to .envrc. Only comment I have is to import `prisma-axiom` in the express example, same way as the script example, currently it imports `src/axiom` which doesn't exist.

**Comment by bahlo** [comment]
Re the Prisma 4.3.1 vs. 4.2.1 error, this can't happen when you use the library because installing `prisma-axiom` won't install Prisma, it'll use the existing one. Still a breaking change on a minor version 🤷 

Will update the express example 👍

**Pull request merged**
